# Generated by Django 6.0.5 on 2026-06-11 00:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(max_length=16)),
                ('total', models.IntegerField(default=0)),
                ('completed', models.IntegerField(default=0)),
                ('failed', models.IntegerField(default=0)),
                ('pr_url', models.URLField(blank=True)),
                ('pr_error', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='InventoryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_filename', models.CharField(max_length=512)),
                ('slug', models.CharField(blank=True, max_length=128)),
                ('title', models.CharField(blank=True, max_length=256)),
                ('classification', models.CharField(blank=True, max_length=64)),
                ('confidence', models.FloatField(blank=True, null=True)),
                ('status', models.CharField(default='pending', max_length=16)),
                ('error_message', models.TextField(blank=True)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='inventory.inventoryrun')),
            ],
        ),
    ]
