# Generated by Django 6.0.5 on 2026-06-12 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryrun',
            name='stage_dir',
            field=models.CharField(blank=True, max_length=512),
        ),
    ]
