"""
Django settings for policycodex_site project.

Generated by 'django-admin startproject' using Django 6.0.5.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from pathlib import Path

from policycodex_site import env as _env

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Working-copy configuration (APP-05). Per-diocese values driven by env
# var or the Settings Policy Repository panel; never hardcoded.
POLICYCODEX_POLICY_REPO_URL = os.environ.get("POLICYCODEX_POLICY_REPO_URL", "")
POLICYCODEX_POLICY_BRANCH = os.environ.get("POLICYCODEX_POLICY_BRANCH", "main")
POLICYCODEX_WORKING_COPY_ROOT = os.environ.get("POLICYCODEX_WORKING_COPY_ROOT", "")

# Configuration-complete flag (APP-21). When False, the startup self-check
# downgrades "working copy missing" failures to Warnings (lets
# `manage.py runserver` start before Settings are configured). Set to True
# once the Settings page has been fully configured. Truthy parser tolerates
# "1", "true", "yes" (case-insensitive); empty string and "0"/"false"/"no"
# are falsy.
_onboarding_raw = os.environ.get("POLICYCODEX_ONBOARDING_COMPLETE", "")
POLICYCODEX_ONBOARDING_COMPLETE = _onboarding_raw.lower() in ("1", "true", "yes")


# Deploy-time knobs (REPO-05). Driven by the environment so the same image
# runs safely in production. Locally, `manage.py runserver` with no env set
# gets DEBUG on and the historical dev key (see policycodex_site/env.py).
DEBUG = _env.get_debug(os.environ)

# DISC-01: SECRET_KEY persists across container restarts via a file in /data.
# The entrypoint generates it on first boot. At test time, a sane default is
# provided so settings imports without a real /data mount.
_secret_key_file = os.environ.get("POLICYCODEX_SECRET_KEY_FILE", "")
if _secret_key_file and os.path.isfile(_secret_key_file):
    with open(_secret_key_file, "r", encoding="utf-8") as _fh:
        SECRET_KEY = _fh.read().strip()
else:
    # Test / dev fallback. Production paths set POLICYCODEX_SECRET_KEY_FILE.
    SECRET_KEY = os.environ.get(
        "DJANGO_SECRET_KEY",
        "django-insecure-test-only-not-for-production",
    )

# Preserve the REPO-05 invariant: in production (DEBUG off), a real key must
# be configured. Without this guard, a non-Docker boot that forgets to set
# POLICYCODEX_SECRET_KEY_FILE would silently fall back to the dev string.
if not DEBUG and SECRET_KEY.startswith("django-insecure-"):
    raise RuntimeError(
        "Refusing to start with the insecure default SECRET_KEY while DEBUG is off. "
        "Set POLICYCODEX_SECRET_KEY_FILE to a file containing a real key, "
        "or set DJANGO_SECRET_KEY in the environment."
    )

ALLOWED_HOSTS = _env.get_allowed_hosts(os.environ)

# AGPL "View Source" footer target (REPO-05). Placeholder org until the
# public GitHub org slug is finalized; override via POLICYCODEX_SOURCE_URL.
POLICYCODEX_SOURCE_URL = _env.get_source_url(os.environ)


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'core',
    'app.working_copy.apps.WorkingCopyAppConfig',
    'app.inventory.apps.InventoryConfig',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'policycodex_site.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'core.context_processors.source_url',
            ],
        },
    },
]

WSGI_APPLICATION = 'policycodex_site.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': _env.get_db_path(os.environ, BASE_DIR),
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'America/Los_Angeles'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'
# Project-level static sources (committed compiled CSS, HTMX, fonts). Without
# this, collectstatic only sees per-app static dirs and would miss policycodex.css.
STATICFILES_DIRS = [BASE_DIR / 'static']
STORAGES = {
    "default": {"BACKEND": "django.core.files.storage.FileSystemStorage"},
    "staticfiles": {
        "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage",
    },
}


# Authentication (APP-02)
# https://docs.djangoproject.com/en/6.0/topics/auth/default/

LOGIN_URL = '/login/'
LOGIN_REDIRECT_URL = '/'
LOGOUT_REDIRECT_URL = '/login/'

# DISC-02: hydrate provider env vars from the credential store. Must run
# AFTER INSTALLED_APPS but before the first LLM/GitHub SDK call. Safe on
# first boot (no-op when no credentials are stored yet).
from app.credentials import hydrate_environment  # noqa: E402
hydrate_environment()
